
BOOTSTRAP_WINDOW_FRAMES = 10

BOOTSTRAP_ACTIVATION_HITS = 2

NEW_TRACK_ACTIVATION_HITS = 4

TENTATIVE_TIMEOUT_SECONDS = 1.0

ACTIVE_TIMEOUT_SECONDS = 2.5

HIGH_CONFIDENCE_THRESHOLD = 0.50

LOW_CONFIDENCE_THRESHOLD = 0.25

NORMAL_MATCH_MAX_COST = 0.88

LOW_CONFIDENCE_RECOVERY_MAX_COST = 0.80

CONTINUITY_RESCUE_MAX_GAP_SECONDS = 1.75

CONTINUITY_RESCUE_MAX_COST = 0.94

REFINE_ENABLED = True

REFINE_MAX_GAP_SECONDS = 1.75

REFINE_MAX_COST = 0.48

REFINE_MAX_ROUNDS = 2
