"""Internal Track constants."""

_LOCATION_HISTORY_WINDOW_FRAMES = 7
_ANCHOR_WEIGHT_EXPONENT = 1.0
_MAX_ANCHOR_DISTANCE_PX = 100.0
_ANCHOR_TIE_DISTANCE_PX = 20.0
_CONFIRMATION_HITS = 3
_ACTIVE_TIMEOUT_FRAMES = 30
_TENTATIVE_TIMEOUT_FRAMES = 15
